---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: download metricbeat db
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: filebeat modules enable system

  - name: enable and configure docker
    command: metricbeat modules enable docker

  - name: setup filebeat
    command: filebeat setup

  - name: setup metricbeat
    command: metricbeat setup

  - name: start filebeat service
    command: service filebeat start

  - name: start metricbeat
    systemd:
      name: metricbeat
      state: started

  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
